name: real_banking
description: Nexus Digital Banking - Customer Mobile App
publish_to: 'none'
version: 1.1.0+2

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  pocketbase: ^0.21.0
  cupertino_icons: ^1.0.8
  intl: ^0.20.2
  shared_preferences: ^2.2.0
  package_info_plus: ^8.0.0
  qr_flutter: ^4.1.0
  mobile_scanner: ^5.0.0
  fl_chart: ^0.68.0
  local_auth: ^2.2.0
  http: ^1.2.0
  image_picker: ^1.1.2
  url_launcher: ^6.3.0
  flutter_animate: ^4.5.0
  cached_network_image: ^3.4.1
  shimmer: ^3.0.0
  flutter_slidable: ^3.1.0
  pin_code_fields: ^8.0.1
  confetti: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
